version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  metric_server:
    image: "rettwalker/metric_server:latest"
    container_name: metric_server
    depends_on:
      - express_server
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
  
  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - metric_server
    ports:
      - 3030:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
  
  express_server:
    build: .
    container_name: express_starter
    ports:
      - "3000:3000"
    volumes:
    - .:/usr/src/app
    command: ["npm", "start"]